Added Images in AUGSD team page and added registration page
ID-BPHC/AUGSD-TD pull request #133
Opened 2021-11-30 13:58 UTC by naresh-golla-design

2021-12-01 11:19 UTC, Kailash0311 commented
Thanks @naresh-golla-design , is this PR tested thoroughly locally and working as expected?

2021-12-01 11:29 UTC, naresh-golla-design commented
> Thanks @naresh-golla-design , is this PR tested thoroughly locally and working as expected?

Yes. It is tested and working.

2021-12-02 07:30 UTC, Kailash0311 approved these changes

2021-12-02 07:38 UTC, sohailrajdev97 commented
Ideally, we should move away from checking-in non website related static content (PDFs etc.) into source control. 

Not needed in this PR, can be taken up separately.

2021-12-02 07:39 UTC, sohailrajdev97 requested changes

2021-12-02 07:39 UTC, sohailrajdev97 commented on routes/admin/portals/control/registration.js
> +let express = require("express");
This is a public facing endpoint. This should not be present in `routes/admin/portals/control`

2021-12-02 07:39 UTC, sohailrajdev97 commented on routes/admin/portals/control/registration.js
> +let express = require("express");
Also, why was this change needed? We are not using this router anywhere.

2021-12-02 08:09 UTC, sohailrajdev97 commented
Please run these commands locally to fix linting

1.`npm install -g grunt-cli`
2. `grunt fix`

2021-12-02 08:24 UTC, sohailrajdev97 commented on routes/admin/portals/control/registration.js
> +let express = require("express");
As discussed offline, please remove this file in a follow-up PR.

2021-12-02 08:24 UTC, sohailrajdev97 approved these changes

2021-12-02 08:25 UTC, merged